grid_map_topic: /uav1/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: -1.0
     data_max: 10.0
