#!/usr/bin/env python3

import sys

from rqt_behavior_tree_command.rqt_behavior_tree_command import BehaviorTreeCommandPlugin
from rqt_gui.main import Main

plugin = 'rqt_behavior_tree_command'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
 